ss_Servicecore: valuesRegistry Class Reference
valuesRegistry Class Reference
#include <valuesRegistry.h>
Public Member Functions
valuesRegistry ()
~valuesRegistry ()
errType addToRegistry (const void *, OrtsType, const char *, size_t)
errType removeFromRegistry (WORD index)
WORD searchIndexByName (const char *, size_t)
const void * getValuePtr (WORD index)
OrtsType getType (WORD index)
const char * getName (WORD index)
size_t quantity ()
Private Attributes
list< registry_record * > registry
Detailed Description
Definition at line 22 of file valuesRegistry.h.
Constructor & Destructor Documentation
valuesRegistry::valuesRegistry ()
Definition at line 11 of file valuesRegistry.cpp.
valuesRegistry::~valuesRegistry ()
Definition at line 12 of file valuesRegistry.cpp.
Member Function Documentation
errType valuesRegistry::addToRegistry (const void * valuePtr, OrtsType type, const char * name, size_t nameLen)
Definition at line 14 of file valuesRegistry.cpp.
References getValuePtr(), registry_record::index, registry_record::name, registry, removeFromRegistry(), searchIndexByName(), registry_record::type, and registry_record::valuePtr.
errType valuesRegistry::removeFromRegistry (WORD index)
Definition at line 37 of file valuesRegistry.cpp.
References registry.
Referenced by addToRegistry().
WORD valuesRegistry::searchIndexByName (const char * name, size_t size)
Definition at line 54 of file valuesRegistry.cpp.
References quantity(), and registry.
Referenced by addToRegistry().
const void * valuesRegistry::getValuePtr (WORD index)
Definition at line 82 of file valuesRegistry.cpp.
References registry.
Referenced by addToRegistry().
OrtsType valuesRegistry::getType (WORD index)
Definition at line 92 of file valuesRegistry.cpp.
References registry.
const char * valuesRegistry::getName (WORD index)
Definition at line 102 of file valuesRegistry.cpp.
References registry.
size_t valuesRegistry::quantity ()
Definition at line 111 of file valuesRegistry.cpp.
References registry.
Referenced by searchIndexByName().
Member Data Documentation
list<registry_record*> valuesRegistry::registry [private]
Definition at line 23 of file valuesRegistry.h.
Referenced by addToRegistry(), getName(), getType(), getValuePtr(), quantity(), removeFromRegistry(), and searchIndexByName().
The documentation for this class was generated from the following files:
src/valuesRegistry/valuesRegistry.h
src/valuesRegistry/valuesRegistry.cpp