ss_Servicecore: src/srvAppLayer/srvAppLayer.cpp File Reference
srvAppLayer.cpp File Reference
Class srvAppLayer implementation.
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <pthread.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <iostream>
#include <queue>
#include "../../rcsLib/ortsTypes/ortsTypes.h"
#include "../../rcsLib/rcsCmd/rcsCmd.h"
#include "../global.h"
#include "../buffer/ssBuffer.h"
#include "../../udp_port/udp_port.h"
#include "../deqUdp/deqUdp.h"
#include "functionNode/param_desc.h"
#include "functionNode/functionNode.h"
#include "srvAppLayer.h"
#include "../functions/commonFuncsMgr.h"
Functions
void * udpSenderThread (void *user)
Thread to sending data to clients from functions answer queue.
void * udpListenerThread (void *user)
Thread to listening requests from clients and form queue of clients requests.
Variables
bool rcvComplete_flag = false
todo msc diagramm
bool sndAllow_flag = false
todo msc diagramm
srvAppLayer * app
One global instance per application.
Detailed Description
Class srvAppLayer implementation.
Author:
Vladimir A. Nosenko (nosenko@ieee.org)
Date:
December, 2010
Copyright (c) 2010 Vladimir A.Nosenko.
The license and distribution terms for this file may be found in the file LICENSE in this distribution
Definition in file srvAppLayer.cpp.
Function Documentation
void* udpSenderThread (void * user)
Thread to sending data to clients from functions answer queue.
Thread also includes work with port opening, initializing and closing.
Definition at line 50 of file srvAppLayer.cpp.
References srvAppLayer::functionsAnswersQueue, deqUdp::sendData(), sndAllow_flag, srvAppLayer::terminate(), srvAppLayer::terminated(), and wUdp.
Referenced by srvAppLayer::StartListening().
void* udpListenerThread (void * user)
Thread to listening requests from clients and form queue of clients requests.
Thread also includes work with port opening, initializing and closing.
Definition at line 102 of file srvAppLayer.cpp.
References srvAppLayer::clientsRequestsQueue, srvAppLayer::getListenerPortNum(), rcvComplete_flag, deqUdp::readData(), srvAppLayer::terminate(), srvAppLayer::terminated(), and wUdp.
Referenced by srvAppLayer::StartListening().
Variable Documentation
bool rcvComplete_flag = false
todo msc diagramm
Flag purpose: synchronize state between receiving clients requests thread and reading for received data
Definition at line 39 of file srvAppLayer.cpp.
Referenced by srvAppLayer::ProcessMessages(), and udpListenerThread().
bool sndAllow_flag = false
todo msc diagramm
Flag purpose: synchronize state between sending clients answers thread and preparing sending data
Definition at line 41 of file srvAppLayer.cpp.
Referenced by srvAppLayer::ProcessMessages(), and udpSenderThread().
srvAppLayer* app
One global instance per application.
Definition at line 43 of file srvAppLayer.cpp.
Referenced by appDeinit(), appInit(), equipListenPolling(), and main().