ss_Servicecore: src/console_out.h File Reference
console_out.h File Reference
aided functions interface header
Functions
void show_help (const char verbose)
Show cmdline help information (--help)
void show_version ()
Show programm version information (--version)
void show_error (const char *msg, const int errcode, const char help)
Show cmdLine parser error.
void internal_error (const char *msg)
Show cmdLine internal error.
const char * optname (const int code, const ap_Option options[])
Convert code with option from cmdLine argument to char buffer.
Variables
char PROGVERSION []
version of programm
char Program_name []
name of programm
char program_name []
filename of programm
char program_year []
copyright year
Detailed Description
aided functions interface header
Author:
Vladimir A. Nosenko (nosenko@ieee.org)
Date:
December, 2010
Copyright (c) 2010 Vladimir A.Nosenko.
The license and distribution terms for this file may be found in the file LICENSE in this distribution
Definition in file console_out.h.
Function Documentation
void show_help (const char verbose)
Show cmdline help information (--help)
Definition at line 36 of file console_out.cpp.
References program_name, and Program_name.
Referenced by process_cmdLine().
void show_version ()
Show programm version information (--version)
Definition at line 58 of file console_out.cpp.
References Program_name, PROGVERSION, and REVISION.
Referenced by process_cmdLine().
void show_error (const char * msg, const int errcode, const char help)
Show cmdLine parser error.
Definition at line 72 of file console_out.cpp.
References program_name.
Referenced by internal_error(), and process_cmdLine().
void internal_error (const char * msg)
Show cmdLine internal error.
Definition at line 86 of file console_out.cpp.
References show_error().
Referenced by process_cmdLine().
const char* optname (const int code, const ap_Option options[])
Convert code with option from cmdLine argument to char buffer.
Definition at line 97 of file console_out.cpp.
References ap_Option::code, and ap_Option::name.
Variable Documentation
char PROGVERSION[]
version of programm
Definition at line 27 of file console_out.cpp.
Referenced by show_version().
char Program_name[]
name of programm
Definition at line 28 of file console_out.cpp.
Referenced by show_help(), and show_version().
char program_name[]
filename of programm
Definition at line 29 of file console_out.cpp.
Referenced by show_error(), and show_help().
char program_year[]
copyright year
Definition at line 30 of file console_out.cpp.