ss_Servicecore: CommonFuncs Class Reference
CommonFuncs Class Reference
#include <CommonFuncs.h>
Public Member Functions
CommonFuncs (ICAppLayer *appl)
~CommonFuncs ()
errType StartCommonFuncs ()
errType StopCommonFuncs ()
Private Attributes
ICAppLayer * appLayer
Detailed Description
Definition at line 3 of file CommonFuncs.h.
Constructor & Destructor Documentation
CommonFuncs::CommonFuncs (ICAppLayer * appl)
Definition at line 40 of file CommonFuncs.cpp.
References appLayer.
CommonFuncs::~CommonFuncs ()
Definition at line 45 of file CommonFuncs.cpp.
Member Function Documentation
errType CommonFuncs::StartCommonFuncs ()
Definition at line 49 of file CommonFuncs.cpp.
References appLayer, ICAppLayer::CreateNewFunction(), FunctionNode::setFuncName(), FunctionNode::setParamDescriptor(), FunctionNode::setParamName(), FunctionNode::setResultDescriptor(), and FunctionNode::setResultName().
Referenced by main().
errType CommonFuncs::StopCommonFuncs ()
Definition at line 117 of file CommonFuncs.cpp.
References appLayer, and ICAppLayer::DeleteFunction().
Member Data Documentation
ICAppLayer* CommonFuncs::appLayer [private]
Definition at line 5 of file CommonFuncs.h.
Referenced by CommonFuncs(), StartCommonFuncs(), and StopCommonFuncs().
The documentation for this class was generated from the following files:
src/Functions/CommonFuncs.h
src/Functions/CommonFuncs.cpp