ss_Servicecore: valueTrig Class Reference
valueTrig Class Reference
#include <valueTrig.h>
Public Member Functions
valueTrig ()
~valueTrig ()
errType setTrigValuePtr (WORD id)
const void * getTrigOldValuePtr ()
WORD getTrigIndex ()
void dbgPrint ()
bool triggerCheck (OrtsType currType, const void *currValue)
errType triggerSet (WORD index, OrtsType type, const void *valuePtr)
DWORD getSize (OrtsType type)
Private Attributes
trigDef_type * trigDef
Detailed Description
Definition at line 18 of file valueTrig.h.
Constructor & Destructor Documentation
valueTrig::valueTrig ()
Definition at line 10 of file valueTrig.cpp.
References trigDef_type::oldValue, and trigDef.
valueTrig::~valueTrig ()
Definition at line 15 of file valueTrig.cpp.
References trigDef_type::oldValue, and trigDef.
Member Function Documentation
errType valueTrig::setTrigValuePtr (WORD id)
const void * valueTrig::getTrigOldValuePtr ()
Definition at line 23 of file valueTrig.cpp.
References trigDef_type::oldValue, and trigDef.
Referenced by triggerCheck().
WORD valueTrig::getTrigIndex ()
Definition at line 24 of file valueTrig.cpp.
References trigDef_type::index, and trigDef.
Referenced by trigList::addValueTrigger().
void valueTrig::dbgPrint ()
Definition at line 26 of file valueTrig.cpp.
References trigDef_type::oldValue, and trigDef.
bool valueTrig::triggerCheck (OrtsType currType, const void * currValue)
Definition at line 54 of file valueTrig.cpp.
References getTrigOldValuePtr().
Referenced by trigList::triggersClock().
errType valueTrig::triggerSet (WORD index, OrtsType type, const void * valuePtr)
Definition at line 77 of file valueTrig.cpp.
References trigDef_type::index, trigDef_type::oldValue, and trigDef.
Referenced by trigList::triggersClock().
DWORD valueTrig::getSize (OrtsType type)
Definition at line 35 of file valueTrig.cpp.
Member Data Documentation
trigDef_type* valueTrig::trigDef [private]
Definition at line 20 of file valueTrig.h.
Referenced by dbgPrint(), getTrigIndex(), getTrigOldValuePtr(), triggerSet(), valueTrig(), and ~valueTrig().
The documentation for this class was generated from the following files:
src/valuesRegistry/valueTrig.h
src/valuesRegistry/valueTrig.cpp