ss_Servicecore: src/Functions/CommonFuncs.h File Reference
CommonFuncs.h File Reference
Classes
class CommonFuncs
Functions
void * EquipListenPolling (void *)
Function Documentation
void* EquipListenPolling (void *)
Definition at line 16 of file CommonFuncs.cpp.
References app, ICAppLayer::equip_read_data(), ICAppLayer::equip_reading_event(), and ICAppLayer::terminated().
Referenced by ICAppLayer::StartListening().