ss_Servicecore: src/arg_parser/carg_parser.h File Reference
carg_parser.h File Reference
Classes
struct ap_Option
struct ap_Record
struct Arg_parser
Enumerations
enum ap_Has_arg { ap_no, ap_yes, ap_maybe }
Functions
char ap_init (Arg_parser *ap, const int argc, const char *const argv[], const ap_Option options[], const char in_order)
void ap_free (Arg_parser *ap)
const char * ap_error (const Arg_parser *ap)
int ap_arguments (const Arg_parser *ap)
int ap_code (const Arg_parser *ap, const int i)
const char * ap_argument (const Arg_parser *ap, const int i)
Enumeration Type Documentation
enum ap_Has_arg
Enumerator:
ap_no
ap_yes
ap_maybe
Definition at line 42 of file carg_parser.h.
Function Documentation
char ap_init (Arg_parser * ap, const int argc, const char *const argv[], const ap_Option options[], const char in_order)
Definition at line 194 of file carg_parser.cpp.
References ap_resize_buffer(), Arg_parser::data, Arg_parser::data_size, Arg_parser::error, Arg_parser::error_size, free_data(), parse_long_option(), parse_short_option(), and push_back_record().
Referenced by process_cmdLine().
void ap_free (Arg_parser * ap)
Definition at line 253 of file carg_parser.cpp.
References Arg_parser::error, Arg_parser::error_size, and free_data().
const char* ap_error (const Arg_parser * ap)
Definition at line 261 of file carg_parser.cpp.
References Arg_parser::error.
Referenced by process_cmdLine().
int ap_arguments (const Arg_parser * ap)
Definition at line 264 of file carg_parser.cpp.
References Arg_parser::data_size.
Referenced by ap_argument(), ap_code(), and process_cmdLine().
int ap_code (const Arg_parser * ap, const int i)
Definition at line 267 of file carg_parser.cpp.
References ap_arguments(), ap_Record::code, and Arg_parser::data.
Referenced by process_cmdLine().
const char* ap_argument (const Arg_parser * ap, const int i)
Definition at line 274 of file carg_parser.cpp.
References ap_arguments(), ap_Record::argument, and Arg_parser::data.
Referenced by process_cmdLine().