ss_Servicecore: deqUdp Class Reference
deqUdp Class Reference
udp communications (based on udp_port) with queues for listening and sending
#include <deqUdp.h>
Public Member Functions
deqUdp (WORD portNum, const char *ip_str="127.0.0.1")
~deqUdp ()
errType sendData (ssBuffer *buf)
Send data to udp port from queued buffer (ssBuffer)
errType readData (ssBuffer *addr, size_t *len, in_addr *ip_from=0, bool peek=false)
Read udp port data to queued buffer (ssBuffer)
Detailed Description
udp communications (based on udp_port) with queues for listening and sending
Definition at line 20 of file deqUdp.h.
Constructor & Destructor Documentation
deqUdp::deqUdp (WORD portNum, const char * ip_str = "127.0.0.1") [inline]
Definition at line 27 of file deqUdp.h.
deqUdp::~deqUdp ()
Definition at line 28 of file deqUdp.cpp.
Member Function Documentation
errType deqUdp::sendData (ssBuffer * buf)
Send data to udp port from queued buffer (ssBuffer)
Parameters:
[in] buf - pointer to queue for sending data
Return values:
err_result_ok - execution was successful
err_result_error - problems with udp sendto function
Todo:
not needed to realize all sendData check ability to use base method sendData of parent class
Definition at line 39 of file deqUdp.cpp.
References ssBuffer::getFrontBlockSize(), and ssBuffer::popBlock().
Referenced by udpSenderThread().
errType deqUdp::readData (ssBuffer * addr, size_t * len, in_addr * ipaddr = 0, bool peek = false)
Read udp port data to queued buffer (ssBuffer)
Parameters:
[in] addr - pointer to queue for readed data
[in] peek - PEEK MODE
[out] len - length of readed data
[out] ipaddr - information about data sender
Return values:
err_result_ok - execution was successful
err_result_error - problems with udp sendto function
Todo:
not needed to realize all sendData check ability to use base method sendData of parent class
Definition at line 77 of file deqUdp.cpp.
References ssBuffer::pushBlock().
Referenced by udpListenerThread().
The documentation for this class was generated from the following files:
src/deqUdp/deqUdp.h
src/deqUdp/deqUdp.cpp