ss_Servicecore: src/arg_parser/carg_parser.cpp File Reference
carg_parser.cpp File Reference
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "carg_parser.h"
Functions
char ap_resize_buffer (void *buf, const int min_size)
char push_back_record (Arg_parser *ap, const int code, const char *argument)
char add_error (Arg_parser *ap, const char *msg)
void free_data (Arg_parser *ap)
char parse_long_option (Arg_parser *ap, const char *const opt, const char *const arg, const ap_Option options[], int *argindp)
char parse_short_option (Arg_parser *ap, const char *const opt, const char *const arg, const ap_Option options[], int *argindp)
char ap_init (Arg_parser *ap, const int argc, const char *const argv[], const ap_Option options[], const char in_order)
void ap_free (Arg_parser *ap)
const char * ap_error (const Arg_parser *ap)
int ap_arguments (const Arg_parser *ap)
int ap_code (const Arg_parser *ap, const int i)
const char * ap_argument (const Arg_parser *ap, const int i)
Function Documentation
char ap_resize_buffer (void * buf, const int min_size)
Definition at line 26 of file carg_parser.cpp.
Referenced by add_error(), ap_init(), and push_back_record().
char push_back_record (Arg_parser * ap, const int code, const char * argument)
Definition at line 37 of file carg_parser.cpp.
References ap_resize_buffer(), ap_Record::argument, ap_Record::code, Arg_parser::data, and Arg_parser::data_size.
Referenced by ap_init(), parse_long_option(), and parse_short_option().
char add_error (Arg_parser * ap, const char * msg)
Definition at line 54 of file carg_parser.cpp.
References ap_resize_buffer(), Arg_parser::error, and Arg_parser::error_size.
Referenced by parse_long_option(), and parse_short_option().
void free_data (Arg_parser * ap)
Definition at line 65 of file carg_parser.cpp.
References ap_Record::argument, Arg_parser::data, and Arg_parser::data_size.
Referenced by ap_free(), and ap_init().
char parse_long_option (Arg_parser * ap, const char *const opt, const char *const arg, const ap_Option options[], int * argindp)
Definition at line 74 of file carg_parser.cpp.
References add_error(), ap_no, ap_yes, ap_Option::code, and push_back_record().
Referenced by ap_init().
char parse_short_option (Arg_parser * ap, const char *const opt, const char *const arg, const ap_Option options[], int * argindp)
Definition at line 146 of file carg_parser.cpp.
References add_error(), ap_no, ap_yes, ap_Option::code, and push_back_record().
Referenced by ap_init().
char ap_init (Arg_parser * ap, const int argc, const char *const argv[], const ap_Option options[], const char in_order)
Definition at line 194 of file carg_parser.cpp.
References ap_resize_buffer(), Arg_parser::data, Arg_parser::data_size, Arg_parser::error, Arg_parser::error_size, free_data(), parse_long_option(), parse_short_option(), and push_back_record().
Referenced by process_cmdLine().
void ap_free (Arg_parser * ap)
Definition at line 253 of file carg_parser.cpp.
References Arg_parser::error, Arg_parser::error_size, and free_data().
const char* ap_error (const Arg_parser * ap)
Definition at line 261 of file carg_parser.cpp.
References Arg_parser::error.
Referenced by process_cmdLine().
int ap_arguments (const Arg_parser * ap)
Definition at line 264 of file carg_parser.cpp.
References Arg_parser::data_size.
Referenced by ap_argument(), ap_code(), and process_cmdLine().
int ap_code (const Arg_parser * ap, const int i)
Definition at line 267 of file carg_parser.cpp.
References ap_arguments(), ap_Record::code, and Arg_parser::data.
Referenced by process_cmdLine().
const char* ap_argument (const Arg_parser * ap, const int i)
Definition at line 274 of file carg_parser.cpp.
References ap_arguments(), ap_Record::argument, and Arg_parser::data.
Referenced by process_cmdLine().