ss_Servicecore: srvAppLayer Class Reference
srvAppLayer Class Reference
Application core layer implementaion.
#include <srvAppLayer.h>
Public Member Functions
srvAppLayer (WORD portNum)
Constructs instance of srvAppLayer and links it to udp port number for listening clients requests.
~srvAppLayer ()
errType CreateNewFunction (functionNode *func)
Method to add new declared function to service layer.
errType DeleteFunction (BYTE id)
Method to delete function from service layer.
errType encodeBlock (rcsCmd *, BYTE **)
Method to encode data from rcsCmd message.
errType StartListening ()
Method to prepare and start base communication engine.
errType StopListening ()
Method to stop base communication engine.
errType equip_reading_event ()
Method to asynchonous polling of equip_listen socket.
errType equip_read_data (BYTE *, size_t *)
Method to read data from equip_listen socket.
errType ProcessMessages ()
Method to make one step of srvAppLayer step.
WORD getListenerPortNum ()
getter for udp port number that listens all clients requests
BYTE terminated ()
Method to check application internal termination signal.
void terminate (BYTE mode=1)
getter for AppTerminated signal
stateVector_type getStateVector ()
getter for ServiceState vector
Public Attributes
ssBuffer * clientsRequestsQueue
Queue that stores received requests from client.
ssBuffer * functionsAnswersQueue
Queue that stores service functions answers to clients.
Private Member Functions
errType decodeMessage (BYTE *dataBlock, DWORD length, rcsCmd *ss_cmd)
step 1. decode recieved message from client
errType execMessage (rcsCmd *ss_cmd)
step 2. send data to requested service function
errType encodeFuncResult (rcsCmd *in_cmd, rcsCmd *out_cmd)
step 3. encode function execution results for sending back to client
errType sendResult (sockaddr_in *sin, rcsCmd *ss_cmd)
step 4. send function answer to client
Private Attributes
BYTE AppTerminated
Application termination process indicator
0 - Application run normally
1 - Applcation need to exit only
2 - Application need exit with reboot.
functionNode * Functions [100]
Service functions array.
BYTE func_quantity
Counter that stores really declared functions quantity.
BYTE ifCount
Counter of ethernet interfaces. No have an idea how to use it.
pthread_t listenerThread
Handle to client requests listening thread.
pthread_t senderThread
Handle to client answers sending thread.
pthread_t equipListenThread
Handle to equipmnent data listening thread.
WORD cpListenerPortNum
settings: Udp port number to listen requests from network clients
udp_port * equip_listen
udp_port instance that associates with listening data from equipment
stateVector_type ServiceState
Service state vector.
Detailed Description
Application core layer implementaion.
This layer delegate network calls to service functions and return back functions results.
Definition at line 46 of file srvAppLayer.h.
Constructor & Destructor Documentation
srvAppLayer::srvAppLayer (WORD portNum)
Constructs instance of srvAppLayer and links it to udp port number for listening clients requests.
Parameters:
[in] portNum - udp port number that will use for clients requests listening
Definition at line 159 of file srvAppLayer.cpp.
References AppTerminated, cpListenerPortNum, func_quantity, and ifCount.
srvAppLayer::~srvAppLayer ()
Definition at line 168 of file srvAppLayer.cpp.
References equip_listen, func_quantity, and Functions.
Member Function Documentation
errType srvAppLayer::decodeMessage (BYTE * dataBlock, DWORD length, rcsCmd * ss_cmd) [private]
step 1. decode recieved message from client
Method to decode message data to function call and parameters set.
Method using method rcsCmd::encode to transform data array to rcsCmd message.
Method checks for correct sign, calling function existing and compares real received data length with header information about data length.
Parameters:
[in] dataBlock - pointer to received bytes array
[in] length - size of received bytes array.
[out] ss_cmd - decoded message.
Return values:
err_result_ok - decoded message is correct.
err_params_decode - params in decoded message is incorrect.
err_not_found - decoded message is calling for non existing function
err_crc_error - decoded message signature is incorrect.
Definition at line 333 of file srvAppLayer.cpp.
References Functions.
Referenced by ProcessMessages().
errType srvAppLayer::execMessage (rcsCmd * ss_cmd) [private]
step 2. send data to requested service function
Method to execute function by id in rcsCmd message.
Method checks for correct params by comparing params with description in commonFuncsMgr or specFuncsMgr.
After requested function calling method changes ServiceState vector and set answer ticket for return value from requested function.
Todo:
ServiceState vector need to change before function calling.
Parameters:
[in] ss_cmd - message with request for function calling.
Return values:
err_result_ok - message executed successfully.
err_params_decode - params in message differs with description.
Definition at line 383 of file srvAppLayer.cpp.
References Functions, stateVector_type::lastFuncId, stateVector_type::lastResult, and ServiceState.
Referenced by ProcessMessages().
errType srvAppLayer::encodeFuncResult (rcsCmd * in_cmd, rcsCmd * out_cmd) [private]
step 3. encode function execution results for sending back to client
Method encoding all executed function results to rcsCmd message.
Method preparing rcsCmd message with making of message signing.
Todo:
Need a refactoring.
Parameters:
[in] in_cmd - message with request for function calling.
[out] out_cmd - message with results from requested function.
Return values:
err_result_ok - message executed successfully.
err_not_found - function to execute was not found.
Definition at line 413 of file srvAppLayer.cpp.
References Functions.
Referenced by ProcessMessages().
errType srvAppLayer::sendResult (sockaddr_in * sfrom, rcsCmd * ss_cmd) [private]
step 4. send function answer to client
Method sending rcsCmd message to needed recepient.
Method preparing data array from rcsCmd message and push data array with address of recepient in to functionsAnswersQueue
Parameters:
[in] sfrom - recepient address.
[in] ss_cmd - message needed to send.
Return values:
err_result_ok - message added to sending queue successfully.
Definition at line 462 of file srvAppLayer.cpp.
References functionsAnswersQueue, ssBuffer::pushBlock(), and wUdp.
Referenced by ProcessMessages().
errType srvAppLayer::CreateNewFunction (functionNode * func)
Method to add new declared function to service layer.
Parameters:
[in] func - functionNode instance
Return values:
err_result_ok - function added successfully
Definition at line 182 of file srvAppLayer.cpp.
References func_quantity, Functions, and functionNode::id().
Referenced by commonFuncsMgr::startCommonFuncs().
errType srvAppLayer::DeleteFunction (BYTE id)
Method to delete function from service layer.
Parameters:
[in] id - functionNode identifier
Return values:
err_result_ok - function deleted successfully
Definition at line 197 of file srvAppLayer.cpp.
References func_quantity, and Functions.
Referenced by commonFuncsMgr::stopCommonFuncs().
errType srvAppLayer::encodeBlock (rcsCmd * ss_cmd, BYTE ** data)
Method to encode data from rcsCmd message.
Parameters:
[in] ss_cmd - rcsCmd message
[out] data - pointer to pointer that will include result of method
Return values:
err_result_ok - Block encoded successfully
Todo:
nobody uses this method. need to be deleted.
Definition at line 214 of file srvAppLayer.cpp.
errType srvAppLayer::StartListening ()
Method to prepare and start base communication engine.
if errors has been occured,method initiate appTerminate signal.
Return values:
err_result_ok - communication engine starts successfully
err_sock_error - udp sockets prerparing error
1. Prepare clientsRequestsQueue.
Queue stores all received messages from clients and clients adresses.
2. Prepare functionsAnswersQueue.
Queue stores all functions answers to clients requests.
3. Start udpListenerThread
Thread listen for udp messages from clients and stores messages in clientsRequestsQueue.
4. Prepare equip_listen.
This is an udp port instance that using to listen data from equipment
5. Start udpSenderThread
Thread sending udp messageds to clients from functionsAnswersQueue
6. Start equipListenPolling
Thread listen for udp messages from equipment
Definition at line 229 of file srvAppLayer.cpp.
References AppTerminated, clientsRequestsQueue, eq_udp_listen_port, equip_listen, equipListenPolling(), equipListenThread, functionsAnswersQueue, ifCount, listenerThread, senderThread, udpListenerThread(), and udpSenderThread().
Referenced by appInit().
errType srvAppLayer::StopListening ()
Method to stop base communication engine.
method initiate appTerminate signal, deletes queues.
Return values:
err_result_ok - engine stopped successfully
Definition at line 274 of file srvAppLayer.cpp.
References AppTerminated, clientsRequestsQueue, functionsAnswersQueue, and verbose_level.
Referenced by appDeinit().
errType srvAppLayer::equip_reading_event ()
Method to asynchonous polling of equip_listen socket.
Todo:
too strange method.
May be it need be deleted.
Return values:
err_result_ok - udp socket received data
Definition at line 301 of file srvAppLayer.cpp.
References equip_listen.
Referenced by equipListenPolling().
errType srvAppLayer::equip_read_data (BYTE * buffer, size_t * sz)
Method to read data from equip_listen socket.
Todo:
too strange method.
May be it need be deleted.
Parameters:
[out] buffer - uses to store recevied data
[out] sz - size in bytes of received data
Return values:
err_result_ok - udp socket received data has been readed
Definition at line 316 of file srvAppLayer.cpp.
References equip_listen.
Referenced by equipListenPolling().
errType srvAppLayer::ProcessMessages ()
Method to make one step of srvAppLayer step.
Method checks at start AppTerminated signal, size of clientsRequestsQueue and rcvComplete_flag before it continuous execution.
Return values:
err_result_ok - one step of engine execution was successfully.
err_not_init - method break execution.
1) Read from clientsRequestsQueue one new request
2) Decode readed request by decodeMessage
3) Execute requested function if decoding was successfully by execMessage
4) Encoding function result ticket if execution was not successfully
5) Encode remains function results be encodeFuncResult
6) Write results to sending queue by sendResult
7) Release allocated memory
8) Sync listening and sending threads by rcvComplete_flag and sndAllow_flag
Definition at line 488 of file srvAppLayer.cpp.
References AppTerminated, clientsRequestsQueue, decodeMessage(), encodeFuncResult(), execMessage(), Functions, ssBuffer::getFrontBlockSize(), ssBuffer::popBlock(), rcvComplete_flag, sendResult(), ssBuffer::size(), and sndAllow_flag.
Referenced by main().
WORD srvAppLayer::getListenerPortNum ()
getter for udp port number that listens all clients requests
Definition at line 565 of file srvAppLayer.cpp.
References cpListenerPortNum.
Referenced by udpListenerThread().
BYTE srvAppLayer::terminated ()
Method to check application internal termination signal.
Return values:
0 - Application runs normally
1 - Application terminating and preparing to exit to the OS
2 - Application terminating and preparing to reboot the OS
Definition at line 148 of file srvAppLayer.cpp.
References AppTerminated.
Referenced by equipListenPolling(), main(), udpListenerThread(), and udpSenderThread().
void srvAppLayer::terminate (BYTE mode = 1)
getter for AppTerminated signal
Definition at line 571 of file srvAppLayer.cpp.
References AppTerminated.
Referenced by udpListenerThread(), and udpSenderThread().
stateVector_type srvAppLayer::getStateVector ()
getter for ServiceState vector
Definition at line 577 of file srvAppLayer.cpp.
References ServiceState.
Member Data Documentation
BYTE srvAppLayer::AppTerminated [private]
Application termination process indicator
0 - Application run normally
1 - Applcation need to exit only
2 - Application need exit with reboot.
Definition at line 48 of file srvAppLayer.h.
Referenced by ProcessMessages(), srvAppLayer(), StartListening(), StopListening(), terminate(), and terminated().
functionNode* srvAppLayer::Functions[100] [private]
Service functions array.
100 functions at maximum.
Todo:
array not the best data structure for this purposes.
Definition at line 53 of file srvAppLayer.h.
Referenced by CreateNewFunction(), decodeMessage(), DeleteFunction(), encodeFuncResult(), execMessage(), ProcessMessages(), and ~srvAppLayer().
BYTE srvAppLayer::func_quantity [private]
Counter that stores really declared functions quantity.
Definition at line 56 of file srvAppLayer.h.
Referenced by CreateNewFunction(), DeleteFunction(), srvAppLayer(), and ~srvAppLayer().
BYTE srvAppLayer::ifCount [private]
Counter of ethernet interfaces. No have an idea how to use it.
Definition at line 57 of file srvAppLayer.h.
Referenced by srvAppLayer(), and StartListening().
pthread_t srvAppLayer::listenerThread [private]
Handle to client requests listening thread.
Definition at line 59 of file srvAppLayer.h.
Referenced by StartListening().
pthread_t srvAppLayer::senderThread [private]
Handle to client answers sending thread.
Definition at line 60 of file srvAppLayer.h.
Referenced by StartListening().
pthread_t srvAppLayer::equipListenThread [private]
Handle to equipmnent data listening thread.
Note:
programm not have equipment data sending thread
Definition at line 61 of file srvAppLayer.h.
Referenced by StartListening().
WORD srvAppLayer::cpListenerPortNum [private]
settings: Udp port number to listen requests from network clients
Definition at line 64 of file srvAppLayer.h.
Referenced by getListenerPortNum(), and srvAppLayer().
udp_port* srvAppLayer::equip_listen [private]
udp_port instance that associates with listening data from equipment
Definition at line 65 of file srvAppLayer.h.
Referenced by equip_read_data(), equip_reading_event(), StartListening(), and ~srvAppLayer().
stateVector_type srvAppLayer::ServiceState [private]
Service state vector.
Definition at line 72 of file srvAppLayer.h.
Referenced by execMessage(), and getStateVector().
ssBuffer* srvAppLayer::clientsRequestsQueue
Queue that stores received requests from client.
Definition at line 76 of file srvAppLayer.h.
Referenced by ProcessMessages(), StartListening(), StopListening(), and udpListenerThread().
ssBuffer* srvAppLayer::functionsAnswersQueue
Queue that stores service functions answers to clients.
Definition at line 77 of file srvAppLayer.h.
Referenced by sendResult(), StartListening(), StopListening(), and udpSenderThread().
The documentation for this class was generated from the following files:
src/srvAppLayer/srvAppLayer.h
src/srvAppLayer/srvAppLayer.cpp