ss_Servicecore: src/SIG_handler.cpp File Reference
SIG_handler.cpp File Reference
System signals handlers manager.
#include <sys/types.h>
#include <unistd.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <arpa/inet.h>
#include "../../rcsLib/ortsTypes/ortsTypes.h"
#include "global.h"
Functions
void term_handler (int i)
signal TERMINATE handling function
void installSIGhandlers (funcVoid func)
signals handlers installer
Variables
funcVoid SIGTERM_handler
pointer to handling function for signal TERMINATE
Detailed Description
System signals handlers manager.
Author:
Vladimir A. Nosenko (nosenko@ieee.org)
Date:
December, 2010
Copyright (c) 2010 Vladimir A.Nosenko.
The license and distribution terms for this file may be found in the file LICENSE in this distribution
Definition in file SIG_handler.cpp.
Function Documentation
void term_handler (int i)
signal TERMINATE handling function
Definition at line 29 of file SIG_handler.cpp.
References SIGTERM_handler, and verbose_level.
Referenced by installSIGhandlers().
void installSIGhandlers (funcVoid func)
signals handlers installer
Definition at line 39 of file SIG_handler.cpp.
References SIGTERM_handler, and term_handler().
Referenced by main().
Variable Documentation
funcVoid SIGTERM_handler
pointer to handling function for signal TERMINATE
Definition at line 24 of file SIG_handler.cpp.
Referenced by installSIGhandlers(), and term_handler().