ss_Servicecore: param_desc Class Reference
param_desc Class Reference
parameter description
#include <param_desc.h>
Public Member Functions
param_desc (OrtsType type, WORD len)
Constructs parameter description with some type and information about storing value length.
param_desc (OrtsType type)
Overloaded constructor that constructs parameter description of a vector type.
~param_desc ()
errType resize (WORD new_size)
Function calling if need to resize of storage for new value or something else...
void * value ()
Getter for pointer of storing value.
WORD length ()
Getter for length of storing value.
OrtsType type ()
Getter for type of storing value.
bool isVector ()
Function checks if type of storing value is a vector.
errType setParam (void *param_val)
Setter function for setting param value.
errType setName (const char *name)
Setter for parameter string name.
errType printParam ()
Print parameter value for debug purposes.
void dbgPrint ()
Print for debug purposes contents of function node (in a hexadecimal notation)
Private Attributes
void * param
pointer to parameter value
char * param_name
parameter string name
WORD _length
length in bytes of storing parameter value
OrtsType _type
bool _isVector
storage value is a vector (one-dimensional array) of simplified values types
Detailed Description
parameter description
parameter description uses in function node parameter declaration
Definition at line 20 of file param_desc.h.
Constructor & Destructor Documentation
param_desc::param_desc (OrtsType type, WORD param_len)
Constructs parameter description with some type and information about storing value length.
Parameters:
type - type (or simplified reference for vector) of storing value
param_len - length in bytes of storing value
Returns:
Definition at line 26 of file param_desc.cpp.
References _isVector, _length, _type, param, and type().
param_desc::param_desc (OrtsType type)
Overloaded constructor that constructs parameter description of a vector type.
Parameters:
type - type of storing value
Returns:
Definition at line 40 of file param_desc.cpp.
References _isVector, _length, _type, and type().
param_desc::~param_desc ()
Definition at line 49 of file param_desc.cpp.
References param, and param_name.
Member Function Documentation
errType param_desc::resize (WORD new_size)
Function calling if need to resize of storage for new value or something else...
Parameters:
new_size - size in bytes of new storage
Returns:
err_result_ok - memory successfully reallocated
err_mem_alloc - error of allocating memory for new size
err_not_init - new size does not differ from old size
Definition at line 63 of file param_desc.cpp.
References _length, and param.
Referenced by setParam().
void * param_desc::value ()
Getter for pointer of storing value.
Returns:
param - pointer to storing value
Definition at line 92 of file param_desc.cpp.
References param.
Referenced by functionNode::getParamPtr(), and functionNode::getResult().
WORD param_desc::length ()
Getter for length of storing value.
Returns:
length - storage size in bytes
Definition at line 83 of file param_desc.cpp.
References _length.
Referenced by functionNode::decodeParams(), functionNode::getAllParamsLength(), functionNode::getAllResultsLength(), functionNode::getResult(), functionNode::getResultLength(), and functionNode::setParamDescriptor().
OrtsType param_desc::type ()
Getter for type of storing value.
Returns:
type - pointer to storing value type
Definition at line 101 of file param_desc.cpp.
References _type.
Referenced by param_desc().
bool param_desc::isVector ()
Function checks if type of storing value is a vector.
Returns:
true - storing value is a vector
false - storing value is a scalar
Definition at line 111 of file param_desc.cpp.
References _type.
errType param_desc::setParam (void * param_val)
Setter function for setting param value.
Parameters:
param_val[in] - pointer to parameter value
Returns:
err_result_ok - value was successfully set
err_params_value - null-pointer error
Definition at line 122 of file param_desc.cpp.
References _isVector, _length, param, and resize().
Referenced by functionNode::decodeParams(), functionNode::setParam(), and functionNode::setResult().
errType param_desc::setName (const char * name)
Setter for parameter string name.
Parameters:
name - name of a parameter.
Returns:
err_result_ok
Definition at line 139 of file param_desc.cpp.
References param_name.
Referenced by functionNode::setParamName(), and functionNode::setResultName().
errType param_desc::printParam ()
Print parameter value for debug purposes.
Returns:
err_result_ok - value was printed successfully
Definition at line 151 of file param_desc.cpp.
References _type, param, and param_name.
Referenced by functionNode::printParams(), and functionNode::printResults().
void param_desc::dbgPrint ()
Print for debug purposes contents of function node (in a hexadecimal notation)
Definition at line 207 of file param_desc.cpp.
References param.
Member Data Documentation
void* param_desc::param [private]
pointer to parameter value
Definition at line 22 of file param_desc.h.
Referenced by dbgPrint(), param_desc(), printParam(), resize(), setParam(), value(), and ~param_desc().
char* param_desc::param_name [private]
parameter string name
Definition at line 23 of file param_desc.h.
Referenced by printParam(), setName(), and ~param_desc().
WORD param_desc::_length [private]
length in bytes of storing parameter value
Definition at line 24 of file param_desc.h.
Referenced by length(), param_desc(), resize(), and setParam().
OrtsType param_desc::_type [private]
Definition at line 25 of file param_desc.h.
Referenced by isVector(), param_desc(), printParam(), and type().
bool param_desc::_isVector [private]
storage value is a vector (one-dimensional array) of simplified values types
Definition at line 27 of file param_desc.h.
Referenced by param_desc(), and setParam().
The documentation for this class was generated from the following files:
src/srvAppLayer/functionNode/param_desc.h
src/srvAppLayer/functionNode/param_desc.cpp