ss_Servicecore: trigList Class Reference
trigList Class Reference
#include <trigList.h>
Public Member Functions
trigList ()
~trigList ()
errType addValueTrigger (valueTrig *)
errType removeValueTrigger (WORD id)
valueTrig * getValueTrigger (WORD id)
valueTrig * searchValueTriggerByValuePtr (const void *)
errType triggersClock (WORD index, OrtsType currType, const void *currValue)
WORD quantity ()
DWORD getFilterListSize ()
errType decode (BYTE *dst_array)
errType encode (BYTE *src_array, DWORD src_array_len)
errType clear ()
void dbgPrint ()
Private Attributes
list< valueTrig * > valueTriggers
DWORD triggersQuantity
Detailed Description
Definition at line 3 of file trigList.h.
Constructor & Destructor Documentation
trigList::trigList ()
Definition at line 14 of file trigList.cpp.
References triggersQuantity.
trigList::~trigList ()
Definition at line 19 of file trigList.cpp.
Member Function Documentation
errType trigList::addValueTrigger (valueTrig * trigger)
Definition at line 24 of file trigList.cpp.
References valueTrig::getTrigIndex(), getValueTrigger(), removeValueTrigger(), and valueTriggers.
errType trigList::removeValueTrigger (WORD id)
Definition at line 43 of file trigList.cpp.
References valueTriggers.
Referenced by addValueTrigger().
valueTrig * trigList::getValueTrigger (WORD id)
Definition at line 62 of file trigList.cpp.
References valueTriggers.
Referenced by addValueTrigger(), and triggersClock().
valueTrig* trigList::searchValueTriggerByValuePtr (const void *)
errType trigList::triggersClock (WORD index, OrtsType currType, const void * currValue)
Definition at line 71 of file trigList.cpp.
References getValueTrigger(), quantity(), valueTrig::triggerCheck(), and valueTrig::triggerSet().
WORD trigList::quantity ()
Definition at line 94 of file trigList.cpp.
References valueTriggers.
Referenced by triggersClock().
DWORD trigList::getFilterListSize ()
errType trigList::decode (BYTE * dst_array)
Definition at line 113 of file trigList.cpp.
errType trigList::encode (BYTE * src_array, DWORD src_array_len)
Definition at line 135 of file trigList.cpp.
errType trigList::clear ()
Definition at line 129 of file trigList.cpp.
References valueTriggers.
void trigList::dbgPrint ()
Definition at line 99 of file trigList.cpp.
Member Data Documentation
list<valueTrig*> trigList::valueTriggers [private]
Definition at line 5 of file trigList.h.
Referenced by addValueTrigger(), clear(), getValueTrigger(), quantity(), and removeValueTrigger().
DWORD trigList::triggersQuantity [private]
Definition at line 6 of file trigList.h.
Referenced by trigList().
The documentation for this class was generated from the following files:
src/valuesRegistry/trigList.h
src/valuesRegistry/trigList.cpp