ss_Servicecore: commonFuncsMgr Class Reference
commonFuncsMgr Class Reference
common functions manager implementation (set of function independs on target)
#include <commonFuncsMgr.h>
Public Member Functions
commonFuncsMgr (srvAppLayer *appl)
~commonFuncsMgr ()
errType startCommonFuncs ()
Declaration of common functions.
errType stopCommonFuncs ()
Undeclaration of common functions.
Private Attributes
srvAppLayer * appLayer
Detailed Description
common functions manager implementation (set of function independs on target)
Definition at line 23 of file commonFuncsMgr.h.
Constructor & Destructor Documentation
commonFuncsMgr::commonFuncsMgr (srvAppLayer * appl)
Definition at line 60 of file commonFuncsMgr.cpp.
References appLayer.
commonFuncsMgr::~commonFuncsMgr ()
Definition at line 65 of file commonFuncsMgr.cpp.
Member Function Documentation
errType commonFuncsMgr::startCommonFuncs ()
Declaration of common functions.
Declares functions:
emergencyShutdown, controlModeChange, getStateVector
Return values:
err_result_ok - declaration was successful
Definition at line 76 of file commonFuncsMgr.cpp.
References appLayer, srvAppLayer::CreateNewFunction(), functionNode::setFuncName(), functionNode::setParamDescriptor(), functionNode::setParamName(), functionNode::setResultDescriptor(), and functionNode::setResultName().
Referenced by main().
errType commonFuncsMgr::stopCommonFuncs ()
Undeclaration of common functions.
Undeclares functions:
emergencyShutdown, controlModeChange, getStateVector
Return values:
err_result_ok - undeclaration was successful
Definition at line 151 of file commonFuncsMgr.cpp.
References appLayer, and srvAppLayer::DeleteFunction().
Member Data Documentation
srvAppLayer* commonFuncsMgr::appLayer [private]
Definition at line 25 of file commonFuncsMgr.h.
Referenced by commonFuncsMgr(), startCommonFuncs(), and stopCommonFuncs().
The documentation for this class was generated from the following files:
src/functions/commonFuncsMgr.h
src/functions/commonFuncsMgr.cpp