ss_Servicecore: ICAppLayer Class Reference
ICAppLayer Class Reference
#include <ICAppLayer.h>
Public Member Functions
ICAppLayer (WORD portNum)
~ICAppLayer ()
errType CreateNewFunction (FunctionNode *func)
errType DeleteFunction (BYTE id)
errType encodeBlock (rcsCmd *, BYTE **)
errType StartListening ()
errType StopListening ()
errType equip_reading_event ()
errType equip_read_data (BYTE *, size_t *)
errType checkTriggers ()
errType ProcessMessages ()
WORD getListenerPortNum ()
BYTE terminated ()
void terminate (BYTE mode=1)
stateVector_type getStateVector ()
Public Attributes
ssBuffer * ICAppLayer_recvBuffer
ssBuffer * ICAppLayer_sendBuffer
Private Member Functions
errType Decode_message (BYTE *dataBlock, DWORD length, rcsCmd *ss_cmd)
errType execMessage (rcsCmd *ss_cmd)
errType prepare_FuncResult (rcsCmd *in_cmd, rcsCmd *out_cmd)
errType sendResult (sockaddr_in *sin, rcsCmd *ss_cmd)
Private Attributes
BYTE AppTerminated
FunctionNode * Functions [100]
BYTE func_quantity
BYTE ifCount
pthread_t listenerThread
pthread_t senderThread
pthread_t equipListenThread
WORD cpListenerPortNum
udp_port * equip_listen
stateVector_type ServiceState
Detailed Description
Definition at line 22 of file ICAppLayer.h.
Constructor & Destructor Documentation
ICAppLayer::ICAppLayer (WORD portNum)
Definition at line 120 of file ICAppLayer.cpp.
References AppTerminated, cpListenerPortNum, func_quantity, and ifCount.
ICAppLayer::~ICAppLayer ()
Definition at line 129 of file ICAppLayer.cpp.
References equip_listen, func_quantity, and Functions.
Member Function Documentation
errType ICAppLayer::Decode_message (BYTE * dataBlock, DWORD length, rcsCmd * ss_cmd) [private]
Definition at line 231 of file ICAppLayer.cpp.
References Functions.
Referenced by ProcessMessages().
errType ICAppLayer::execMessage (rcsCmd * ss_cmd) [private]
Definition at line 270 of file ICAppLayer.cpp.
References Functions, stateVector_type::lastFuncId, stateVector_type::lastResult, and ServiceState.
Referenced by ProcessMessages().
errType ICAppLayer::prepare_FuncResult (rcsCmd * in_cmd, rcsCmd * out_cmd) [private]
Definition at line 291 of file ICAppLayer.cpp.
References Functions.
Referenced by ProcessMessages().
errType ICAppLayer::sendResult (sockaddr_in * sin, rcsCmd * ss_cmd) [private]
Definition at line 332 of file ICAppLayer.cpp.
References ICAppLayer_sendBuffer, ssBuffer::pushBlock(), and wUdp.
Referenced by ProcessMessages().
errType ICAppLayer::CreateNewFunction (FunctionNode * func)
Definition at line 137 of file ICAppLayer.cpp.
References func_quantity, Functions, and FunctionNode::id().
Referenced by commonFuncsMgr::startCommonFuncs().
errType ICAppLayer::DeleteFunction (BYTE id)
Definition at line 146 of file ICAppLayer.cpp.
References func_quantity, and Functions.
Referenced by commonFuncsMgr::stopCommonFuncs().
errType ICAppLayer::encodeBlock (rcsCmd * ss_cmd, BYTE ** data)
Definition at line 156 of file ICAppLayer.cpp.
errType ICAppLayer::StartListening ()
Definition at line 165 of file ICAppLayer.cpp.
References AppTerminated, eq_udp_listen_port, equip_listen, equipListenPolling(), equipListenThread, ICAppLayer_recvBuffer, ICAppLayer_sendBuffer, ifCount, listenerThread, senderThread, udpListenerThread(), and udpSenderThread().
Referenced by appInit().
errType ICAppLayer::StopListening ()
Definition at line 197 of file ICAppLayer.cpp.
References AppTerminated, ICAppLayer_recvBuffer, ICAppLayer_sendBuffer, and verbose_level.
Referenced by appDeinit().
errType ICAppLayer::equip_reading_event ()
Definition at line 219 of file ICAppLayer.cpp.
References equip_listen.
Referenced by equipListenPolling().
errType ICAppLayer::equip_read_data (BYTE * buffer, size_t * sz)
Definition at line 227 of file ICAppLayer.cpp.
References equip_listen.
Referenced by equipListenPolling().
errType ICAppLayer::checkTriggers ()
Definition at line 351 of file ICAppLayer.cpp.
errType ICAppLayer::ProcessMessages ()
Definition at line 356 of file ICAppLayer.cpp.
References AppTerminated, Decode_message(), execMessage(), Functions, ssBuffer::getFrontBlockSize(), ICAppLayer_recvBuffer, ssBuffer::popBlock(), prepare_FuncResult(), rcvComplete_flag, sendResult(), ssBuffer::size(), and sndAllow_flag.
Referenced by main().
WORD ICAppLayer::getListenerPortNum ()
Definition at line 433 of file ICAppLayer.cpp.
References cpListenerPortNum.
Referenced by udpListenerThread().
BYTE ICAppLayer::terminated ()
Definition at line 114 of file ICAppLayer.cpp.
References AppTerminated.
Referenced by equipListenPolling(), main(), udpListenerThread(), and udpSenderThread().
void ICAppLayer::terminate (BYTE mode = 1)
Definition at line 438 of file ICAppLayer.cpp.
References AppTerminated.
Referenced by udpListenerThread(), and udpSenderThread().
stateVector_type ICAppLayer::getStateVector ()
Definition at line 443 of file ICAppLayer.cpp.
References ServiceState.
Member Data Documentation
BYTE ICAppLayer::AppTerminated [private]
Definition at line 24 of file ICAppLayer.h.
Referenced by ICAppLayer(), ProcessMessages(), StartListening(), StopListening(), terminate(), and terminated().
FunctionNode* ICAppLayer::Functions[100] [private]
Definition at line 25 of file ICAppLayer.h.
Referenced by CreateNewFunction(), Decode_message(), DeleteFunction(), execMessage(), prepare_FuncResult(), ProcessMessages(), and ~ICAppLayer().
BYTE ICAppLayer::func_quantity [private]
Definition at line 26 of file ICAppLayer.h.
Referenced by CreateNewFunction(), DeleteFunction(), ICAppLayer(), and ~ICAppLayer().
BYTE ICAppLayer::ifCount [private]
Definition at line 27 of file ICAppLayer.h.
Referenced by ICAppLayer(), and StartListening().
pthread_t ICAppLayer::listenerThread [private]
Definition at line 29 of file ICAppLayer.h.
Referenced by StartListening().
pthread_t ICAppLayer::senderThread [private]
Definition at line 30 of file ICAppLayer.h.
Referenced by StartListening().
pthread_t ICAppLayer::equipListenThread [private]
Definition at line 31 of file ICAppLayer.h.
Referenced by StartListening().
WORD ICAppLayer::cpListenerPortNum [private]
Definition at line 33 of file ICAppLayer.h.
Referenced by getListenerPortNum(), and ICAppLayer().
udp_port* ICAppLayer::equip_listen [private]
Definition at line 35 of file ICAppLayer.h.
Referenced by equip_read_data(), equip_reading_event(), StartListening(), and ~ICAppLayer().
stateVector_type ICAppLayer::ServiceState [private]
Definition at line 45 of file ICAppLayer.h.
Referenced by execMessage(), and getStateVector().
ssBuffer* ICAppLayer::ICAppLayer_recvBuffer
Definition at line 49 of file ICAppLayer.h.
Referenced by ProcessMessages(), StartListening(), StopListening(), and udpListenerThread().
ssBuffer* ICAppLayer::ICAppLayer_sendBuffer
Definition at line 50 of file ICAppLayer.h.
Referenced by sendResult(), StartListening(), StopListening(), and udpSenderThread().
The documentation for this class was generated from the following files:
src/ICAppLayer/ICAppLayer.h
src/ICAppLayer/ICAppLayer.cpp