ss_Servicecore: src/ICAppLayer/ICAppLayer.cpp File Reference
ICAppLayer.cpp File Reference
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <pthread.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <iostream>
#include <queue>
#include "../../rcsLib/ortsTypes/ortsTypes.h"
#include "../../rcsLib/rcsCmd/rcsCmd.h"
#include "../global.h"
#include "../buffer/ssBuffer.h"
#include "../../udp_port/udp_port.h"
#include "../deqUdp/deqUdp.h"
#include "FunctionNode/param_desc.h"
#include "FunctionNode/FunctionNode.h"
#include "ICAppLayer.h"
#include "../Functions/CommonFuncs.h"
Functions
void * udpSenderThread (void *user)
void * udpListenerThread (void *user)
Variables
bool rcvComplete_flag = false
bool sndAllow_flag = false
ICAppLayer * app
Function Documentation
void* udpSenderThread (void * user)
Definition at line 28 of file ICAppLayer.cpp.
References ICAppLayer::ICAppLayer_sendBuffer, deqUdp::sendData(), sndAllow_flag, ICAppLayer::terminate(), ICAppLayer::terminated(), and wUdp.
Referenced by ICAppLayer::StartListening().
void* udpListenerThread (void * user)
Definition at line 75 of file ICAppLayer.cpp.
References ICAppLayer::getListenerPortNum(), ICAppLayer::ICAppLayer_recvBuffer, rcvComplete_flag, deqUdp::readData(), ICAppLayer::terminate(), ICAppLayer::terminated(), and wUdp.
Referenced by ICAppLayer::StartListening().
Variable Documentation
bool rcvComplete_flag = false
Definition at line 23 of file ICAppLayer.cpp.
Referenced by ICAppLayer::ProcessMessages(), and udpListenerThread().
bool sndAllow_flag = false
Definition at line 24 of file ICAppLayer.cpp.
Referenced by ICAppLayer::ProcessMessages(), and udpSenderThread().
ICAppLayer* app
Definition at line 26 of file ICAppLayer.cpp.
Referenced by appDeinit(), appInit(), equipListenPolling(), and main().