ss_Servicecore: src/functions/commonFuncsMgr.cpp File Reference
commonFuncsMgr.cpp File Reference
Class commonFuncsMgr interface header.
#include <pthread.h>
#include <netinet/in.h>
#include <queue>
#include "../../rcsLib/ortsTypes/ortsTypes.h"
#include "../buffer/ssBuffer.h"
#include "../../rcsLib/rcsCmd/rcsCmd.h"
#include "../../udp_port/udp_port.h"
#include "../srvAppLayer/functionNode/param_desc.h"
#include "../srvAppLayer/functionNode/functionNode.h"
#include "../srvAppLayer/srvAppLayer.h"
#include "commonFuncsMgr.h"
#include "functions.h"
Functions
void * equipListenPolling (void *user)
Thread to polling listen udp for equipment data.
Detailed Description
Class commonFuncsMgr interface header.
Author:
Vladimir A. Nosenko (nosenko@ieee.org)
Date:
December, 2010
Copyright (c) 2010 Vladimir A.Nosenko.
The license and distribution terms for this file may be found in the file LICENSE in this distribution
Definition in file commonFuncsMgr.cpp.
Function Documentation
void* equipListenPolling (void * user)
Thread to polling listen udp for equipment data.
Calls equipListenProcessing for decoding data received from equipment
Return values:
user
Todo:
Listening equipment answer - status vector:
Definition at line 35 of file commonFuncsMgr.cpp.
References app, srvAppLayer::equip_read_data(), srvAppLayer::equip_reading_event(), and srvAppLayer::terminated().
Referenced by srvAppLayer::StartListening().