ss_Servicecore: ssBuffer Class Reference
ssBuffer Class Reference
list (deque) implementaion for storing ssBlock elements.
#include <ssBuffer.h>
Public Member Functions
ssBuffer ()
~ssBuffer ()
errType pushBlock (sockaddr_in *, BYTE *, DWORD len)
push datablock to queue
DWORD popBlock (sockaddr_in *, BYTE *)
pop datablock from queue
errType getBlockPtrAt (int index, ssBlock *block)
read item from queue by index
DWORD getFrontBlockSize ()
get first in queue (front) block size in bytes
DWORD size ()
return length (items quantity) of queue
void dbgPrint ()
Print for debug purposes contents of stored queue (in a hexadecimal notation)
Private Attributes
deque< ssBlock * > buffer
Detailed Description
list (deque) implementaion for storing ssBlock elements.
deque uses to organize sending or receiving queue
Definition at line 33 of file ssBuffer.h.
Constructor & Destructor Documentation
ssBuffer::ssBuffer ()
Definition at line 23 of file ssBuffer.cpp.
ssBuffer::~ssBuffer ()
Definition at line 28 of file ssBuffer.cpp.
Member Function Documentation
errType ssBuffer::pushBlock (sockaddr_in * addr, BYTE * block, DWORD len)
push datablock to queue
copies data from block and addr pointers to new memory locations
Parameters:
[in] addr - recepient address (owner of datablock)
[in] block - datablock
[in] len - size in bytes of datablock
Return values:
err_result_ok - pushing was successfully
Definition at line 41 of file ssBuffer.cpp.
References ssBlock::addr_in, ssBlock::data, and ssBlock::dataLen.
Referenced by deqUdp::readData(), and srvAppLayer::sendResult().
DWORD ssBuffer::popBlock (sockaddr_in * addr, BYTE * block)
pop datablock from queue
copies data from queue to block and addr pointers
block and addr need to be allocated before calling this method.
queue element will be removed from queue
Parameters:
[in] addr - recepient address (owner of datablock)
[in] block - datablock
Return values:
lenght - size in bytes of readed datablock
Definition at line 77 of file ssBuffer.cpp.
References ssBlock::addr_in, ssBlock::data, and ssBlock::dataLen.
Referenced by srvAppLayer::ProcessMessages(), and deqUdp::sendData().
errType ssBuffer::getBlockPtrAt (int index, ssBlock * block)
read item from queue by index
Parameters:
[in] index - queue item index
[out] block - readed queue item
Definition at line 99 of file ssBuffer.cpp.
DWORD ssBuffer::getFrontBlockSize ()
get first in queue (front) block size in bytes
need to be prepared for reading next queue element
Return values:
dataLen - size in bytes of data block
Definition at line 61 of file ssBuffer.cpp.
References ssBlock::dataLen.
Referenced by srvAppLayer::ProcessMessages(), and deqUdp::sendData().
DWORD ssBuffer::size ()
return length (items quantity) of queue
Definition at line 112 of file ssBuffer.cpp.
Referenced by dbgPrint(), and srvAppLayer::ProcessMessages().
void ssBuffer::dbgPrint ()
Print for debug purposes contents of stored queue (in a hexadecimal notation)
Definition at line 123 of file ssBuffer.cpp.
References ssBlock::addr_in, ssBlock::data, ssBlock::dataLen, and size().
Member Data Documentation
deque<ssBlock*> ssBuffer::buffer [private]
Definition at line 35 of file ssBuffer.h.
The documentation for this class was generated from the following files:
src/buffer/ssBuffer.h
src/buffer/ssBuffer.cpp